config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'oauth_login', sign_out: 'oauth_logout', sign_up: 'oauth_register'}, controllers: {omniauth_callbacks: 'omniauth'}
  # STATIC ROUTES
  root "static#home"
  get '/about-us', to: "static#about"
  get '/services', to: "static#services"
  get '/help', to: "static#help"

  # USER ROUTES && COMPANY ROUTES
  resources :company do
    resources :users
    resources :client
  end

  resources :user do
    resources :notes
  end

  # CLIENT ROUTES AND NESTED CLIENT CONTACT ROUTES
  resources :client do
    resources :client_contacts
    resources :notes
  end
  # CASE ROUTES
  resources :case
end

app/models/client.rb
class Client < ApplicationRecord
    belongs_to :company
    has_many :notes
    has_many :client_contacts
    has_many :users, through: :notes
    accepts_nested_attributes_for :client_contacts
    
    validates_presence_of :name, :size, :industry, :client_contacts, {message: " cannot be left blank."}
    validates :size, numericality: { only_integer: true }
    validates :name, uniqueness: true
    
    extend FriendlyId
    friendly_id :name, use: :slugged
end

app/controllers/client_controller.rb
class ClientController < ApplicationController

    before_action :find_client, only: [:show, :edit, :update, :destroy]
    before_action :is_guest?

    def index
        @clients = Client.all
    end

    def show
    end

    def new
        @client = Client.new
        @client.client_contacts.build
    end

    def create
        @client = Client.new(client_params)
        @client.company_id = current_company.id
        if @client.save
            redirect_to client_path(@client)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @client.update(client_params)
            redirect_to company_client_path(@client.company, @client)
        else
            render :edit
        end
    end

    def destroy
        @client.client_contacts.destroy_all
        @client.destroy
        redirect_to company_path(current_company)
    end

    private 

    def client_params
        params.require(:client).permit(:name, :business, :size, :industry, :company_id, client_contacts_attributes: [:first_name, :last_name, :email, :phone, :title, :client_id])
    end

    def find_client
        @client = Client.friendly.find(params[:id])
    end

end

app/helpers/client_helper.rb
module ClientHelper
    def admin_client_functions
        if current_user.is_admin?
            content_tag(:a, "Delete Client Account", href: client_path(@client), method: "delete", data: {confirm: "Are you sure you want to remove #{@client.name} client account??"})
        else
            content_tag(:p, "Normal User Account")
        end
    end
end

app/views/client/_form.html.erb
<% if @client.errors.any? %>
    <ul>
    <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>
<%=content_tag(:label, "Client's Business name:")%><br/>
<%= f.text_field :name, placeholder: "Enter Business Name"%><br/>

<%=content_tag(:label, "Client's Business Size:")%><br/>
<%= f.text_field :size, placeholder: "Number of employees"%><br/>

<%=content_tag(:label, "Client's Industry:")%><br/>
<%= f.text_field :industry, placeholder: "Clients Industry Name"%><br/>

<%= content_tag(:p) do %>
    <%=content_tag(:h2, "Create a new contact for the Client")%>
<% end %>

app/views/client/edit.html.erb
<%= content_tag(:h2, "Edit #{@client.name.pluralize} account.")%>
<%= form_for @client, path: edit_company_client_path(current_company, @client), url: "/company/#{current_company.id}/client/#{@client.id}/" , id: "edit-client-form" do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit %>
<% end %>

app/views/client/new.html.erb
<%= form_for @client, path: new_client_path, url: "/company/#{current_company.id}/client/" , id: "new-client-form" do |f| %>
    <%= content_tag(:h2, "Create a new client account.")%>
    <%= render 'form', f: f %>
    <hr/>

    <%= f.fields_for :client_contacts do |form_client_contact| %>
        <%=content_tag(:label, "Contact's first name:")%><br/>
        <%= form_client_contact.text_field :first_name, id: "contact_first_name", placeholder: "Enter first name" %><br/>
       
        <%=content_tag(:label, "Contact's last name:")%><br/>       
        <%= form_client_contact.text_field :last_name, id: "contact_last_name", placeholder: "Enter last name" %><br/>
        
        <%=content_tag(:label, "Contact's email:")%><br/>
        <%= form_client_contact.email_field :email, id: "contact_email", placeholder: "Enter contact's email" %><br/>
        
        <%=content_tag(:label, "Contact's phone number:")%><br/>
        <%= form_client_contact.telephone_field :phone, id: "contact_phone", placeholder: "Enter Phone number" %><br/>
        
        <%=content_tag(:label, "Title of contact (ex: CEO, Receptionist, etc.):")%><br/>
        <%= form_client_contact.text_field :title, id: "contact_title", placeholder: "Enter contact's title" %><br/><br/>
    <% end %>
    <%= f.submit "Create Client"%>
<% end %>

app/views/client/show.html.erb
Client's name: <%= @client.name %><br/>
Business Size: <%= @client.size %><br/>
<%= link_to "New Note", new_client_note_path(@client) %>
<%= link_to "New Contact", new_client_client_contact_path(@client) %>
<%= link_to "Edit Client Information", edit_company_client_path(current_company, @client)%>
<%= admin_client_functions %>
<h3>Clients Notes</h3>
<% @client.notes.each do |note| %>
    <%= note.content %><br/>
<% end %>

<h3>Clients Contacts</h3>
<% @client.client_contacts.each do  |cc| %>
    <%= link_to cc.first_name + " " + cc.last_name, client_client_contact_path(cc.client, cc) %>
<% end %>