config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'oauth_login', sign_out: 'oauth_logout', sign_up: 'oauth_register'}, controllers: {omniauth_callbacks: 'omniauth'}
  # STATIC ROUTES
  root "static#home"
  get '/about-us', to: "static#about"
  get '/services', to: "static#services"
  get '/help', to: "static#help"

  # USER ROUTES && COMPANY ROUTES
  resources :company do
    resources :users
    resources :client
  end

  resources :user do
    resources :notes
  end

  # CLIENT ROUTES AND NESTED CLIENT CONTACT ROUTES
  resources :client do
    resources :client_contacts
    resources :notes
  end
  # CASE ROUTES
  resources :case
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, omniauth_providers: [:google_oauth2]
    belongs_to :company
    has_many :notes
    has_many :clients, through: :notes

    validates_presence_of :first_name, :last_name, :username, :email, {message: " cannot be left blank."}
    validates :password, length: { in: 8..20 }
    validates :username, :email, uniqueness: true
    def self.create_from_provider_data(provider_data)
      where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
        if provider_data.info.first_name.nil? || provider_data.info.last_name.nil?
          user.first_name, user.last_name = provider_data.info.name.split 
        else
          user.first_name = provider_data.info.first_name
          user.last_name = provider_data.info.last_name
          user.username = provider_data.info.name.split.join("-")
        end
        user.email = provider_data.info.email
        user.password = Devise.friendly_token[8, 20] # password not provided by the providers, so we create our own
      end
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :find_user, only: [:index, :show, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to login_path
        else 
            render :new
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    def destroy
        @user.destroy
        reset_session
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation, :email, :company_id)
    end

    def find_user
        @user = User.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:index, :show, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to login_path
        else 
            render :new
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    def destroy
        @user.destroy
        reset_session
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation, :email, :company_id)
    end

    def find_user
        @user = User.find(params[:id])
    end
end

app/helpers/user_helper.rb
module UserHelper
    def admin?
        if current_user.is_admin?
            content_tag(:p, "ADMIN ACCOUNT")
        else
            content_tag(:p, "Normal User Account")
        end
    end
end

app/views/user/_form.html.erb
<% if @user && @user.errors.any? %>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>
<%= f.text_field :first_name, id: "first_name", placeholder: "Enter first Name" %><br/><br/>
<%= f.text_field :last_name, placeholder: "Enter last name" %><br/><br/>
<%= f.text_field :username, placeholder: "Create a username" %><br/><br/>
<%= f.text_field :password, type: "password", placeholder: "Create a password" %><br/><br/>
<%= f.text_field :password_confirmation, type: "password", placeholder: "Confirm password" %><br/><br/>
<%= f.text_field :email, placeholder: "example@gmail.com" %><br/><br/>

app/views/user/edit.html.erb
<%= form_for @user, path: company_user_path(@user.company, @user), method: :patch do |f| %>
    <h4> Edit User information <h4/><br/>
    <%= render 'form', f: f %>
    <%= f.submit "Update User" %>
<% end %>

app/views/user/new.html.erb
<%= form_for :user, url: '/user', method: :post do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit "Create User" %>
<% end %>

app/views/user/show.html.erb
<%= admin? %>
<%= content_tag(:div, id: "user-info-card") do %>
    <label>Username: </label><%= @user.username %><br/>
    <label>First Name: </label><%= @user.first_name %><br/>
    <label>Last Name: </label><%= @user.last_name %><br/>
    <label>Email Address: </label><%= @user.email %><br/>
    <%= link_to "Edit your user information", edit_company_user_path(current_user.company, current_user)%><br/>
    <%= link_to "Delete user account", company_user_path(current_user.company, current_user), method: :delete, data: {confirm: "Are you sure you want to delete your account?"} %>
<% end %>