config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'oauth_login', sign_out: 'oauth_logout', sign_up: 'oauth_register'}, controllers: {omniauth_callbacks: 'omniauth'}
  # STATIC ROUTES
  root "static#home"
  get '/about-us', to: "static#about"
  get '/services', to: "static#services"
  get '/help', to: "static#help"

  # USER ROUTES && COMPANY ROUTES
  resources :company do
    resources :users
    resources :client
  end

  resources :user do
    resources :notes
  end

  # CLIENT ROUTES AND NESTED CLIENT CONTACT ROUTES
  resources :client do
    resources :client_contacts
    resources :notes
  end
  # CASE ROUTES
  resources :case
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :clients
    has_many :users
    accepts_nested_attributes_for :users
    has_many :client_contacts, through: :clients
    has_many :notes, through: :users

    validates_presence_of :name, :industry, :size, :users, {message: " cannot be left blank."}
    validates :size, numericality: { only_integer: true }
    validates :name, uniqueness: true

    extend FriendlyId
    friendly_id :name, use: :slugged
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
    before_action :find_company, only: [:show, :edit, :update, :destroy]
    
    def index
        @companies = Company.all
    end
    
    def show
    end

    def new
        @company = Company.new
        @company.users.build
    end

    def create
        @company = Company.new(company_params)
        if @company.save
            redirect_to root_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @company.update(company_params)
            redirect_to company_path(@company)
        else
            render :edit
        end
    end

    def destroy
        @company.users.destroy_all
        @company.clients.destroy_all
        @company.destroy
        reset_session
        redirect_to root_path
    end

    private 

    def company_params
        params.require(:company).permit(:name, :industry, :size, users_attributes: [:first_name, :last_name, :username, :password, :password_confirmation, :email, :company_id])
    end

    def find_company
        @company = current_company
    end
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/company/_form.html.erb
<% if @company.errors.any? %>
    <ul>
    <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<%= f.text_field :name, placeholder: "Enter Business Name" %><br/><br/>
<%= f.text_field :industry, placeholder: "Business Industry"  %><br/><br/>
<%= f.text_field :size, placeholder: "How many Employees?" %><br/><br/>

app/views/company/edit.html.erb
<%= content_tag(:h1, "Edit Company information below")%>
<%= form_for @company, path: company_index_path do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit %><br/>
<% end %>

app/views/company/index.html.erb
<% @companies.each do |company| %>
    <%= company.name %><br/>
<% end %>

app/views/company/new.html.erb
<%= content_tag(:h1, "Register new Company and User")%>
<%= form_for @company, url: company_index_path do |f| %>
    <%= content_tag(:h2, "Company information")%>

    <%# partial with a local 'f' passed %>
    <%= render 'form', f: f %>
    <hr>
    <%= content_tag(:h1, "Register new user below") %>

    <%# Nested fields to create user when creating a new company. %>
    <%= f.fields_for :users do |f| %>
        <%= render 'user/form', f: f%>
    <% end %>
    <%= f.submit "Create Company" %><br/>
<% end %>

app/views/company/show.html.erb
<%= content_tag(:h1, current_user.company.name)%>

<%= content_tag(:p) do %>
    <%= content_tag(:h1, "Swift Solutions CRM")%>
    <%= link_to "New Client", new_company_client_path(@company) %>
    <h3>Choose a client to edit:</h3>
    
    <%= link_to "Edit Company Info", edit_company_path(@company) %>

    <h3>Delete the Company account:</h3>
    <%= link_to "Delete Company Account", company_path(@company), method: "delete", data: {confirm: "WARNING. THIS WILL REMOVE ALL INFORMATION RELATED\n TO COMPANY, REMOVING THE ACCOUNT...CONTINUE?"} %>
<% end %>

<h2>View All Clients!</h2>
<% @company.clients.each do |client| %>
    <%= link_to client.name, company_client_path(@company, client) %>
<% end %>