config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'oauth_login', sign_out: 'oauth_logout', sign_up: 'oauth_register'}, controllers: {omniauth_callbacks: 'omniauth'}
  # STATIC ROUTES
  root "static#home"
  get '/about-us', to: "static#about"
  get '/services', to: "static#services"
  get '/help', to: "static#help"

  # USER ROUTES && COMPANY ROUTES
  resources :company do
    resources :users
    resources :client
  end

  resources :user do
    resources :notes
  end

  # CLIENT ROUTES AND NESTED CLIENT CONTACT ROUTES
  resources :client do
    resources :client_contacts
    resources :notes
  end
  # CASE ROUTES
  resources :case
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% cache do %>
      <title><%= @page_title %></title>
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="keywords" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Red+Hat+Text:wght@700&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-dark bg-primary">
        <% if user_signed_in? %>
          <%= home_link %>
          <%= link_to "About Us", about_us_path, class: "nav-item" %>
          <%= link_to "Services", services_path, class: "nav-item" %>
          <%= link_to "Logout", destroy_user_session_path, class: "nav-item", method: :delete%>
        <% else %>
          <p><%= link_to "Login", new_user_session_path, class: "nav-item"%> / <%= link_to "Register Company", new_company_path, class: "nav-item"%></p>
        <% end %>
      </nav>
    </header>
    <section>
      <%= yield %>
    </section>

    <footer>
    </footer>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swift Solutions CRM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Red+Hat+Text:wght@700&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark bg-primary">
      <%= link_to "Pipeline", client_index_path, class: "nav-item" %>
      <%= link_to "Help", help_path, class: "nav-item" %>
      <%= link_to "Logout", logout_path, class: "nav-item"%>
    </nav>
    <%= yield %>
  </body>
</html>